setup
setUp

	entries := (CZBibParser
		parse:
			'	
				
@book{Fabr17a,
	Annote = {book},
	Author = {J. Fabry and S. Ducasse},
	Keywords = {skipdoi kzSmalltalk kzBook lse-pub},
	Publisher = {Square Bracket Associates},
	Title = {The Spec UI Framework},
	Url = {http://books.pharo.org},
	pages = {84},
	Hal-Id= {hal-01612690},
	Year = {2017}}
				
				
@techreport{Dias14b,
	Annote = {technicalReport},
	Author = {Mart\''in Dias and Uquillas G\''{o}mez, Ver\''onica  and Damien Cassou and St\''ephane Ducasse},
	Hal-Id = {hal-01093496},
	Inria = {RMOD},
	Institution = {INRIA Lille},
	Keywords = {lse-pub},
	Title = {Software Integration Questions: A Quantitative Survey with \&},
	Url = {https://hal.inria.fr/hal-01093496},
	Year = {2014}}
	
	
@inproceedings{Rocha18a,
	annote = {internationalworkshop},
	author={H. Rocha and S. Ducasse},
	booktitle={1st International Workshop on Emerging Trends in Software Engineering for Blockchain (WETSEB)},
	title={Preliminary Steps Towards Modeling Blockchain Oriented Software},
	pages={1-6},
	abstract={Even though blockchain is mostly popular for its cryptocurrency,
smart contracts have become a very prominent blockchain application.
Smart contracts are like classes that can be called by client
applications outside the blockchain. Therefore it is possible to develop
blockchain-oriented software (BOS) that implements part of
the business logic in the blockchain by using smart contracts. Currently,
there is no design standard to model BOS. Since modeling is
an important part of designing a software, developers may struggle
to plan their BOS. In this paper, we show three complementary
modeling approaches based on well-known software engineering
models and apply them to a BOS example. Our goal is to start the
discussion on specialized blockchain modeling notations.},
	keywords={Blockchain;Modeling;Smart Contracts;UML;BPMN;ER Model; lse-pub kzBlockchain},
	month={may},
	year={2018}}
	
') entries